# ------------------------------
# MYSQL DATABASE CONFIGURATION
# ------------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/mred?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
spring.datasource.username=demouser1
spring.datasource.password=Demouser1@

# ------------------------------
# Hibernate
# ------------------------------
spring.jpa.hibernate.ddl-auto=none

# ------------------------------
# Logging
# ------------------------------
logging.level.com.cbk.devconstruction=ERROR
logging.level.org.springframework.web=ERROR
logging.level.org.hibernate=ERROR
logging.path=/images/test/mred/logs/

# ------------------------------
# Nginx Server Properties
# ------------------------------
nginx.directory=/images/test/mred/images/
nginx.url=https://beta1.cbkdevops.com/test/mred/images/
nginx.fileDirectory=/images/test/mred/attachments/
nginx.fileUrl=https://beta1.cbkdevops.com/test/mred/attachments/
nginx.importFolder=/images/test/mred/excel/imports/
nginx.exportFolder=/images/test/mred/excel/exports/

# ------------------------------
# JMX default Domain
# ------------------------------
spring.jmx.default-domain=mred

# ------------------------------
# Profile
# ------------------------------
spring.config.activate.on-profile=live
