# ------------------------------
# MYSQL DATABASE CONFIGURATION
# ------------------------------
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ------------------------------
# Hibernate
# ------------------------------
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.show-sql=true
spring.jpa.properties.javax.persistence.lock.timeout=30000
spring.jpa.properties.hibernate.id.new_generator_mappings=false
spring.jpa.properties.hibernate.format_sql=true

# ------------------------------
# JWT Properties
# ------------------------------
app.jwt.secret= JWTSuperSecretKey
#7 day (seconds)
app.jwt.expirationins = 604800

# ------------------------------
# Multipart_File Size
# ------------------------------
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB

# ------------------------------
# Spring Batch Properties
# ------------------------------
spring.batch.job.enabled=false
spring.batch.initialize-schema=always

# ------------------------------
# Active Profile
# ------------------------------
spring.profiles.active=@spring.profiles.active@
#
#server.port=8081
