# ------------------------------
# MYSQL DATABASE CONFIGURATION
# ------------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/hostel_directory_system?useUnicode=yes&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root

# ------------------------------
# Hibernate
# ------------------------------
spring.jpa.hibernate.ddl-auto=update

# ------------------------------
# Logging
# ------------------------------
logging.level.com.cbk.devconstruction=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.path=logs

# ------------------------------
# Nginx Server Properties
# ------------------------------
nginx.directory=C:\\nginx\\html\\devconstruction\\images\\
nginx.url=http://localhost:8081/devconstruction/images/
nginx.fileDirectory=C:\\nginx\\html\\devconstruction\\attachments\\
nginx.fileUrl=http:\\localhost:8081/devconstruction/attachments/
nginx.importFolder=C:\\nginx\\html\\devconstruction\\excel\\imports\\
nginx.exportFolder=C:\\nginx\\html\\devconstruction\\excel\\exports\\

# ------------------------------
# JMX default Domain
# ------------------------------
spring.jmx.default-domain=devconstruction

# ------------------------------
# Profile
# ------------------------------
spring.config.activate.on-profile=dev

